package database.vikiLibraRy.databaseObjects;

import api.mediaWiki.requestObjects.ParsedPage;
import helper.wikiTextParsing.UnityUIElement;
import helper.wikiTextParsing.UnityUITuple;

import java.util.List;

/**
 * A parsed page of wikipedia, holding the actual content
 */
public class WikiPage extends ParsedPage {

    /**
     * A short summarization of this pages content. This is generated by the NLP-Pipeline
     */
    private String summarizedText;

    /**
     * This is the wikitext parsed as ui text
     */
    private List<UnityUITuple> parsedUITuples;

    public void setParsedUIText(List<UnityUITuple> tuples){
        this.parsedUITuples = tuples;
    }
}
